extends: 'eslint:recommended'
env:
  es6: true
  node: true
parser: 'babel-eslint'
parserOptions:
  sourceType: module
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - never
  quote-props:
    - error
    - as-needed
  keyword-spacing:
    - error
  no-console:
    - off
  prefer-const:
    - warn
  require-atomic-updates:
    - off
